import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<body className="bg-gray-50">
        <main className="min-h-screen">
          <nav className="bg-blue-600 text-white p-4">
            <div className="container mx-auto flex justify-between">
              <h1 className="text-xl font-bold">{metadata.title}</h1>
              <div className="space-x-4">
                <a href="/weighbridge-search" className="hover:underline">Search</a>
                <a href="/grn-form" className="hover:underline">New GRN</a>
              </div>
            </div>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
